name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install LLVM
        run: sudo apt-get install -y llvm

      - name: Build aria
        run: make build/aria

      - name: Test Aria
        run: make test
