name: Package Deployment

on: 
  push:
    tags:
      - '*.*.*'

jobs:
  publish_aur_package:
    name: Publish AUR package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
     
      - name: Generate PKGBUILD
        run: ./ci/github_actions/generate_pkgbuild.sh

      - name: Publish aria to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2.5.0
        with:
          pkgname: aria
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Release ${{ github.ref_name }}
